config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'home/top'
  get 'home/about'
  get 'contacts/new'
  get 'contacts/create'
  root 'manngas#index'
  get 'searchs/search', to:'search#search'
  get '/post/hashtag/:name', to: "manngas#hashtag"

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :edit, :update] do
    collection do
     get :favorite
    end
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :manngas, only: [:index, :show] do
    resource :bookmarks, only: %i[create destroy]
    get :bookmarks, on: :collection
    resources :posts, only: [:new,:create,:destroy, :edit, :update]
    resource  :favorites, only: [:create, :destroy]
  end

  resources :contacts, only: [:new,:create]
  get 'genres/:id' => 'genres#show', as: 'genre_show'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :contacts, only: [:index, :show]
    resources :manngas, only: [:index, :new, :create, :show, :edit, :update] do
        #Ajaxで動くアクションのルートを作成
      collection do
        get 'genre_children', defaults: { format: 'json' }
        resources :genres, only: [:index, :create, :edit, :update]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_manngas, through: :favorites, source: :mannga
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit]
	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user), notice: "編集が完了しました！"
		else
			render 'edit'
		end
	end
	def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
    end

    def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
    end

    def favorite
    @favorite_manngas = current_user.favorite_manngas
    end

    private
	def user_params
		params.require(:user).permit(:last_name, :first_name, :nick_name, :description, :email, :password, :password_confirmation)
	end

	#url直接防止　メソッドを自己定義してbefore_actionで発動。
   def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <h9>edit_user</h9>

    <%= form_for @user do |f| %>
      <div class="form-horizontal">
        <div class="form-group">
          <div class="col-xs-3">
            <%= f.label :last_name, "名前" , class: "control-label" %>
          </div>
          <div class="col-xs-3">(姓)<%= f.text_field :last_name,class: "name form-control" %></div>
          <div class="col-xs-3">(名)<%= f.text_field :first_name, class: "form-control" %></div>
        </div>

        <div class="form-group">
          <div class="col-xs-3">
            <%= f.label :email, "メールアドレス", class: "control-label" %>
          </div>
          <div class="col-xs-6"><%= f.email_field :email, class: "form-control"%></div>
        </div>

        <div class="form-group">
          <div class="col-xs-3">
            <%= f.label :description, "紹介文", class: "control-label" %>
          </div>

          <div class="col-xs-6">
            <%= f.text_area :description, class: "form-control", rows: "8",
            placeholder:'好きな漫画やジャンルなどを書いてみよう！！' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-xs-3">
            <%= f.label :nick_name, "ニックネーム", class: "control-label" %>
        </div>
        <div class="col-xs-6"><%= f.text_field :nick_name,class: "form-control" %></div>
      </div>


      <div class="actions">
        <div class="col-xs-3">
            <%= f.submit "編集内容を保存する", class: " btn btn-warning col-xs-offset-3" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="container">
    <div class="row">
    	<div class="font_z">likes <i class="glyphicon glyphicon-heart"style="color: red;"></i></div>

    	<table class="table">
			<thead>
				<tr>
					<th><h3>mannga_image</h3></th>
					<th><h3>mannga_title</h3></th>
					<th><h3>mannga_author</h3></th>
					<th></th>
					<th></th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @favorite_manngas.each do |mannga| %>
				<tr>

					<td> <%= attachment_image_tag mannga, :image, id: "preview", size: '150x150', fallback: "no_image.jpg" %></td>
					<td><%= link_to mannga_path(mannga) do %>
						<%= mannga.name%>
							<% end %>
						</td>
					<td><%= mannga.author%></td>
					<td></td>
					<td></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="font_z">
		    user_porofil
		</div>
	</div>

	<div class="row">
		<div class="col-xs-4">
			<table class="table">
				<tr>
					<th><h3>name</h3></th>
					<td><%= @user.last_name%>　<%= @user.first_name %></td>
				</tr>
				<tr>
					<th><h3>description</h3></th>
					<td><%= @user.description %></td>
				</tr>
				<tr>
					<th><h3>nick_name</h3></th>
					<td><%= @user.nick_name %></td>
				</tr>
				<tr>
					<th><h3>email</h3></th>
					<td><%= @user.email %></td>
				</tr>
				<tr>
					<th><h3>follow</h3></th>
					<td><%= link_to following_user_path(@user) do %>
						<%= @user.followings.count %>
						<% end %>
						</td>
				</tr>
				<tr>
				    <th><h3>followers</h3></th>
				    <td><%= link_to followers_user_path(@user) do %>
				    	<%= @user.followers.count %>
				    		<% end %>
				    	</td>
				</tr>
				</table>
			</table>
			<% if user_signed_in? %>
			  <%= render 'relationships/follow_button', user: @user, relotionship: @relationship %>
			<% end %>
			<% if current_user == @user %>
			<%= link_to "編集する", edit_user_path, class: "btn btn-warning" %>
			<%= link_to "パスワードを変更する", edit_user_registration_path, class: "btn btn-warning" %>
			<% end %>
	    </div>



		<div class="col-xs-8">
            <div class="font_z">rebyu</div>

			    <table class="table"style="">
					<thead>
						<tr>
							<th><h3>mannga_name</h3></th>
							<th><h3>title</h3></th>
							<th><h3>body</h3></th>
							<th><h3>rate</h3></th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @posts.each do |post| %>
							<tr>
								<td><%= post.mannga.name %></td>
								<td> <%= post.title %></td>
								<td><%= post.body %></td>
								<td><div id="star-rate-<%= post.id %>"></div>
				                <script>
				                $('#star-rate-<%= post.id %>').raty({
				                  size: 36,
				                  starOff:  '<%= asset_path('star-off.png') %>',
				                  starOn : '<%= asset_path('star-on.png') %>',
				                  starHalf: '<%= asset_path('star-half.png') %>',
				                  half: true,
				                  readOnly: true,
				                  score: <%= post.rate %>,
				                  });
				                </script>
									<% end %></td>
								<td>
							</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class = "container">
　  <div class="row">
	    <div class="col-xs-8 col-xs-offset-2">

　          <h3>Follow Users</h3>

			<table class="table">
				<thead>
					<tr>
						<th>nick_name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @user.followings.each do |user| %>
						<tr>

							<td><%= user.nick_name%></td>
							<td>フォロ数ー :<%= user.followings.count %></td>
							<td>フォロワー数 : <%= user.followers.count %></td>
							<td><% unless current_user == user %>
							    <% if current_user.following?(user) %>
									<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
									    <%= f.hidden_field :follow_id, value: user.id %>
									    <%= f.submit 'フォロー外す',class: 'btn btn-danger btn-block'%>
									<% end %>
									<% else %>
									    <%= form_for(current_user.relationships.build) do |f| %>
									      <%= f.hidden_field :follow_id, value: user.id %>
									      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
									    <% end %>
									<% end %>
							    <% end %>
							<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
       </div>
    </div>
</div>

app/views/users/show_follower.html.erb
<div class = "container">
    <div class="row">
	    <div class="col-xs-3-col-xs-offset-2">

			<h3>Follower Users</h3>

			<table class="table">
				<thead>
					<tr>
						<th>nick_name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @user.followers.each do |user| %>
						<tr>
							<td></td>
							<td><%= user.nick_name%></td>
							<td>フォロ数ー :<%= user.followings.count %></td>
							<td>フォロワー数 : <%= user.followers.count %></td>
							<td><% unless current_user == user %>
								<% if current_user.following?(user) %>
								    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
								    <%= f.hidden_field :follow_id, value: user.id %>
								    <%= f.submit 'フォロー外す', class: 'btn btn-danger btn-block' %>
								    <% end %>
								<% else %>
								    <%= form_for(current_user.relationships.build) do |f| %>
								    <%= f.hidden_field :follow_id, value: user.id %>
								      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
								    <% end %>
								  <% end %>
								<% end %>
							<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
        </div>
    </div>
</div>