config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'home/top'
  get 'home/about'
  get 'contacts/new'
  get 'contacts/create'
  root 'manngas#index'
  get 'searchs/search', to:'search#search'
  get '/post/hashtag/:name', to: "manngas#hashtag"

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :edit, :update] do
    collection do
     get :favorite
    end
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :manngas, only: [:index, :show] do
    resource :bookmarks, only: %i[create destroy]
    get :bookmarks, on: :collection
    resources :posts, only: [:new,:create,:destroy, :edit, :update]
    resource  :favorites, only: [:create, :destroy]
  end

  resources :contacts, only: [:new,:create]
  get 'genres/:id' => 'genres#show', as: 'genre_show'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :contacts, only: [:index, :show]
    resources :manngas, only: [:index, :new, :create, :show, :edit, :update] do
        #Ajaxで動くアクションのルートを作成
      collection do
        get 'genre_children', defaults: { format: 'json' }
        resources :genres, only: [:index, :create, :edit, :update]
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :mannga
  validates :user_id, uniqueness: { scope: :mannga_id }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :mannga
end

app/models/genre.rb
class Genre < ApplicationRecord
	 has_many :manngas
	 has_ancestry
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: {maximum:99}
  has_many :micropost_hashtags
end

app/models/mannga.rb
class Mannga < ApplicationRecord
	attachment :image
  belongs_to :genre
  has_many :micropost_hashtags, dependent: :destroy
	has_many :posts
  has_many :bookmarks, dependent: :destroy
	has_many :favorites, dependent: :destroy
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    # boardのお気に入り判定 → vies側で呼び出し
    def bookmark_by?(user)
      bookmarks.where(user_id: user.id).exists?
    end


    #DBへのコミット直前に実施する
  after_create do
    mannga = Mannga.find_by(id: self.id)
    hashtags  = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      MicropostHashtags.create(mannga_id: mannga.id, hashtag_id: tag.id)
    end
  end

  before_update do
    MicropostHashtags.where(mannga_id: self.id).destroy_all
    hashtags = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      MicropostHashtags.create(mannga_id: self.id, hashtag_id: tag.id)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :mannga

  validates :title, presence: true
  validates :body, presence: true
  validates :rate, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
    belongs_to :follow, class_name: 'User'

    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_manngas, through: :favorites, source: :mannga
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	    @manngas = Mannga.find(Favorite.group(:mannga_id).order('count(mannga_id) desc').limit(3).pluck(:mannga_id))
	    render layout:false
	end

	def about
	end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manngas_helper.rb
module ManngasHelper
	def render_with_hashtags(description)
    description.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>漫画レビュー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">
  </head>



    <body>
        <div class="about_title">
         about
        </div>

        <div class="about-s">
         現在プログラマー を目指しています。<br>
         ポートフォリオでこちらのWEBアプリケーションを作成いたしました。<br>
         元々漫画が好きで漫画読む際にレビューや口コミなどを見て読む漫画を決めていたので<br>
         漫画のレビューサイトを作成いたしました。
        </div>

        <div class="about">
         name : kazuya.s
        </div>
    </body>
    <h3></h3><h3></h3>
</html>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>漫画レビュー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">
  </head>


    <header class="navbar navbar-fixed-top">
        <div class="nav_top">
            <div class="container">
                <nav>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to ' home',home_top_path %></li>
                        <li><%= link_to ' about',home_about_path  %></li>
                        <li><%= link_to ' manngas',root_path  %></li>
                        <li><%= link_to ' sign_up', new_user_session_path%></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>


    <body>
        <div class="book_image"style="background-size: cover; background-position: center;">
            <div class="welcom-text">
                <h8>welcome
                    <p> mannga_review</p>
                </h8>
            </div>
        </div>


        <div class="back"style="margin-top: 10px">
            <div class="row">
                <div class="col-xs-12"style=" text-align: center;">
                  <h7>01</h7>
                  <div class="top_x">好きな漫画を見つけてレビューを書いてみよう！</div>
                </div>
            </div>
        </div>

         <div class="row">
            <div class="col-xs-12"style=" text-align: center;">
              <h7>02</h7>
              <div class="top_x">好きな漫画を見つけていいねをしよう！</div>
            </div>
        </div>

        <div class="back">
            <div class="row">
                <div class="col-xs-12"style=" text-align: center;">
                  <h7>03</h7>
                  <div class="top_x">気になるレビューを見つけたらその人をフォローしてみよう！</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12"style=" text-align: center;">
              <h7>04</h7>
              <div class="top_x">何か追加して欲しい機能や漫画があれば問合せてみよう！</div>
            </div>
        </div>

        <div class="back">
            <div class="row">
                <div class="col-xs-12"style=" text-align: center;">
                  <h7>05</h7>
                  <div class="top_x">気になる漫画があれば検索してみよう！</div>
                </div>
            </div>
        </div>

        <div class="books_image"style="background-size: cover; background-position: center;">
            <div class="books_font">
                <div class="">On this site　Find your favorite book  <br>
                    You can like and post!Let's find your favorite<br>
                    and post!
                </div>
        　　</div>
           <a href="/users/sign_up" class="pochitto_btn_blue">sing_up</a>
        </div>
　  </body>
</html>