config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'home/top'
  get 'home/about'
  get 'contacts/new'
  get 'contacts/create'
  root 'manngas#index'
  get 'searchs/search', to:'search#search'
  get '/post/hashtag/:name', to: "manngas#hashtag"

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :edit, :update] do
    collection do
     get :favorite
    end
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :manngas, only: [:index, :show] do
    resource :bookmarks, only: %i[create destroy]
    get :bookmarks, on: :collection
    resources :posts, only: [:new,:create,:destroy, :edit, :update]
    resource  :favorites, only: [:create, :destroy]
  end

  resources :contacts, only: [:new,:create]
  get 'genres/:id' => 'genres#show', as: 'genre_show'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :contacts, only: [:index, :show]
    resources :manngas, only: [:index, :new, :create, :show, :edit, :update] do
        #Ajaxで動くアクションのルートを作成
      collection do
        get 'genre_children', defaults: { format: 'json' }
        resources :genres, only: [:index, :create, :edit, :update]
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :mannga
  validates :user_id, uniqueness: { scope: :mannga_id }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :mannga
end

app/models/genre.rb
class Genre < ApplicationRecord
	 has_many :manngas
	 has_ancestry
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: {maximum:99}
  has_many :micropost_hashtags
end

app/models/mannga.rb
class Mannga < ApplicationRecord
	attachment :image
  belongs_to :genre
  has_many :micropost_hashtags, dependent: :destroy
	has_many :posts
  has_many :bookmarks, dependent: :destroy
	has_many :favorites, dependent: :destroy
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    # boardのお気に入り判定 → vies側で呼び出し
    def bookmark_by?(user)
      bookmarks.where(user_id: user.id).exists?
    end


    #DBへのコミット直前に実施する
  after_create do
    mannga = Mannga.find_by(id: self.id)
    hashtags  = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      MicropostHashtags.create(mannga_id: mannga.id, hashtag_id: tag.id)
    end
  end

  before_update do
    MicropostHashtags.where(mannga_id: self.id).destroy_all
    hashtags = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      MicropostHashtags.create(mannga_id: self.id, hashtag_id: tag.id)
    end
  end
end

app/models/micropost_hashtags.rb
class MicropostHashtags < ApplicationRecord
  belongs_to :mannga
  belongs_to :hashtag

  validates  :mannga_id, presence: true
  validates  :hashtag_id,   presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :mannga

  validates :title, presence: true
  validates :body, presence: true
  validates :rate, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
    belongs_to :follow, class_name: 'User'

    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_manngas, through: :favorites, source: :mannga
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/admin/manngas_controller.rb
class Admin::ManngasController < ApplicationController
	before_action :set_genre_parent, only: [:new, :create, :edit, :update]
	before_action :authenticate_admin!


	def new
		@mannga = Mannga.new
	end

	def index
		@manngas = Mannga.all
	end


	def show
		@mannga = Mannga.find(params[:id])
	end

	def edit
		@mannga = Mannga.find(params[:id])
	end

	def create
		@mannga = Mannga.new(mannga_params)
      if @mannga.save
    	 redirect_to admin_manngas_path
      else
        flash[:error_messages] = @mannga.errors.full_messages
        render 'new'
      end
 	end

	def update
		@mannga = Mannga.find(params[:id])
		@genre = @mannga.genre
		@mannga.update(mannga_params)
		redirect_to admin_mannga_path(@mannga)
	end

	def hashtag
	    @user = current_user
	    @tag = Hashtag.find_by(hashname: params[:name])
	    @manngas = []
	    MicropostHashtags.where(hashtag_id: @tag.id).includes(:mannga).each do |micropost_hashtag|
	    	@manngas << micropost_hashtag.mannga
	    end

    end


    # 親カテゴリーが選択された後に動くアクション
    def genre_children
        #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
        @genre_children = Genre.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
    end

	private
	def mannga_params
	params.require(:mannga).permit(:name, :description, :image, :author, :genre_id)
	end

	def set_genre_parent
	  @genre_parent_array = [{ name: "---", id: "---"}]
	  Genre.where(ancestry: nil).each do |parent|
      @genre_parent_array << { name: parent.name, id: parent.id }
      end
	end
end

app/controllers/manngas_controller.rb
class ManngasController < ApplicationController

	  def index
  	  @manngas = Mannga.page(params[:page]).reverse_order #一覧表示するためにManngaモデルの情報を全てくださいのall
  	  @parents = Genre.where(ancestry: nil)
    end

    def show
  	  @mannga = Mannga.find(params[:id])
      @posts = @mannga.posts #その漫画に紐づくレビュー
      @parents = Genre.where(ancestry: nil)
      @average_mannga_post = Post.group(:mannga_id).average(:rate)
    end

    def hashtag
	    @user = current_user
      @parents = Genre.where(ancestry: nil)
	    @tag = Hashtag.find_by(hashname: params[:name])
	    @manngas = []
	    MicropostHashtags.where(hashtag_id: @tag.id).includes(:mannga).each do |micropost_hashtag|
	    	@manngas << micropost_hashtag.mannga
	    end
    end

    def bookmarks
    @manngas = current_user.bookmark_boards.includes(:user).recent
    end
end

app/helpers/admin/manngas_helper.rb
module Admin::ManngasHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manngas_helper.rb
module ManngasHelper
	def render_with_hashtags(description)
    description.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/manngas/_mannga.html.erb
<h3>mannga</h3>

<% if current_user  %>
  <div style='display: inline; float: right;'>
    <%= link_to icon('fas', 'pen'), edit_mannga_path(mannga), id: :"button-edit-#{mannga.id}" %>
    <%= link_to icon('fas', 'trash-alt'), mannga_path(mannga), id: :"button-delete-#{mannga.id}",method: :delete, data: { confirm: '削除してよろしいですか？' } %>
  </div>
<% else %>
  <div style='display: inline; float: right;'>
     <%= render 'boards/bookmark_area', mannga: mannga %>
  </div>
<% end %>

app/views/manngas/hashtag.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h9 style="border-bottom: 1px solid silver; margin-bottom: 10px;">Genre</h9>
			<div class="row">
				<% @parents.each do |parent| %>
					<div class="row" style="margin-left: 10px; padding-bottom: 5px;">
						<%= link_to genre_show_path(parent.id) do %>
						<h3><%= parent.name %> >></h3>
						<% end %>
					</div>
						<% parent.children.each do |child| %>
							<div class="row" style="margin-left: 10px; padding-bottom: 5px; padding-left: 50px;">
								<%= link_to genre_show_path(child.id) do %>
								<%= child.name %>
								<% end %>
							</div>
						<% end %>
				<% end %>
			</div>
		</div>
		<div class="col-xs-9">
		 	<div class="row">
		 		<h3 style="text-center">mannga_all</h3>
			    <% @manngas.each do |mannga| %>
			    	<div class="col-xs-3">
			    		<div class="row">
			    			<div class="col-xs-12">
			                  <%= attachment_image_tag mannga, :image, id: "preview", size: '150x150', fallback: "no_image.jpg" %>
			                </div>
			            </div>

			    	    <div class="row">
			    		    <div class="col-xs-12">
			    		    	<%= link_to mannga.name, mannga_path(mannga) %>
			    		    </div>
			    		</div>
			    	    <div class="row">
			    			<div class="col-xs-12">
			    				<%= mannga.author%>
			    			</div>
			    		</div>
			    	</div>
			    <% end %>
		    </div>
		</div>
	</div>
</div>

app/views/manngas/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h9 style="border-bottom: 1px solid silver; margin-bottom: 10px;">Genre</h9>
			<div class="row">
				<% @parents.each do |parent| %>
					<div class="row" style="margin-left: 10px; padding-bottom: 5px;">
						<%= link_to genre_show_path(parent.id) do %>
						<h3><%= parent.name %> >></h3>
						<% end %>
					</div>
						<% parent.children.each do |child| %>
							<div class="row" style="margin-left: 10px; padding-bottom: 5px; padding-left: 50px;">
								<%= link_to genre_show_path(child.id) do %>
								<%= child.name %>
								<% end %>
							</div>
						<% end %>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
		 	<div class="row">
		 		<h3 style="text-center">mannga_all</h3>
			    <% @manngas.each do |mannga| %>
			    	<div class="col-xs-3">
			    		<div class="row">
			    			<div class="col-xs-12">
			                  <%= attachment_image_tag mannga, :image, id: "preview", size: '150x150', fallback: "no_image.jpg" %>
			                </div>
			            </div>

			    	    <div class="row">
			    		    <div class="col-xs-12">
			    		    	<%= link_to mannga.name, mannga_path(mannga) %><br>
			    		    </div>
			    		</div>
			    	    <div class="row">
			    			<div class="col-xs-12">
			    				<%= mannga.author%>
			    			</div>
			    		</div>
			    		  <div class="row">
			    			<div class="col-xs-12">
			    			</div>
			    		</div>
			    	</div>
			    <% end %>
		    </div>
		    <%= paginate @manngas %>
		</div>
	</div>
</div>

app/views/manngas/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <h9 style="border-bottom: 1px solid silver; margin-bottom: 10px;">Genre</h9>
      <div class="row">
        <% @parents.each do |parent| %>
          <div class="row" style="margin-left: 10px; padding-bottom: 5px;">
            <%= link_to genre_show_path(parent.id) do %>
            <h3><%= parent.name %> >></h3>
            <% end %>
          </div>
            <% parent.children.each do |child| %>
              <div class="row" style="margin-left: 10px; padding-bottom: 5px; padding-left: 50px;">
                <%= link_to genre_show_path(child.id) do %>
                <%= child.name %>
                <% end %>
              </div>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-xs-9">
      <div class="font_z"> mannga </div>
      <div class="row">
      	<div class="col-xs-3">
          <%= attachment_image_tag @mannga, :image, id: "preview", size: '200x200', fallback: "no_image.jpg" %>
        </div>



      <div class="row">
        <div class="col-xs-6">
          <div class="manga">
            <h3>name</h3>
            <%= @mannga.name %><br>

            <div id="star-rate-<%= @mannga.id %>"></div>
                <script>
                $('#star-rate-<%= @mannga.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= @mannga.posts.average(:rate).to_f.round(1) %>
                  });
                </script>

            <h3>description</h3>
            <%= render_with_hashtags(@mannga.description) %>
            <h3>genre</h3>
            <%= @mannga.genre.name %>
　　　　　　　<% if user_signed_in? %>
              <% if @mannga.favorited_by?(current_user) %>
                <%= link_to mannga_favorites_path(@mannga), method: :delete do %>
                <i class="glyphicon glyphicon-heart"style="color: red;"></i>
                <%= @mannga.favorites.count %>
                <% end %>
                </li>
                <% else %>
                  <%= link_to mannga_favorites_path(@mannga), method: :post do %>
                <i class="glyphicon glyphicon-heart"></i>
                 <%= @mannga.favorites.count %>
                <% end %>
              <% end %>
            <% end %>
            <% if user_signed_in? %>
             <%= link_to "レビューを書く", new_mannga_post_path(@mannga) %>
             <% end %>
          </div>
        </div>
      </div>



      <div class="row">
        <div class="col-xs-9">
          <h3> rebyu </h3>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th><h3>user_name</h3></th>
                <th></th>
                <th><h3>rate</h3></th>
                <th><h3>tile</h3></th>
                <th><h3>body</h3></th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <% @posts.each do |post| %>
              <tbody>
              　  <tr>
                    <td>
                    <%= link_to user_path(post.user.id) do %>
                    <%= post.user.last_name%>
                    <% end %>
                    </td>
                    <td>
                    </td>
                    <td>
                    <div id="star-rate-<%= post.id %>"></div>
                    <script>
                    $('#star-rate-<%= post.id %>').raty({
                      size: 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= post.rate %>,
                      });
                    </script>
                    </td>
                    <td><%= post.title %></td>
                    <td><%= post.body %></td>
                    <td> <% if current_user == post.user %>
                      <%= link_to '口コミを編集',edit_mannga_post_path(mannga_id: @mannga, id: post), method: :get, class:'btn btn-warning' %></td>
                      <td><%= link_to '口コミを削除',mannga_post_path(mannga_id: @mannga, id: post) , method: :delete, class:'btn btn-warning' %>
                    <% end %></td>
                  </tr>
                </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>